### ISSUE TITLE
Access denied / not synced

### ISSUE THREAD

**Issue by JuergenUniVie** [philbertphotos/osticket-multildap-auth-plugin#69]
osTicket-Version | v1.17.3 (ca95150)
Apache/2.4.37 (rocky) OpenSSL/1.1.1k mod_fcgid/2.3.9
MySQL-Version | 10.3.35
PHP-Version | 8.2.5
Plugin Version 1.8

I can't log into the AD server via the plugin, and it won't sync either. 
Nothing is shown in the log that an attempt was made to sync. However, 
LDAP on the server works, tested with a small php file.

any idea?

Thank you!

**Comment by philbertphotos** [comment]
1. Turn on Debug.
2. Does the ldap test work with in the plugin.
3. Show me a sanitize version of your configuration

Syncing should work I went through great pains to fix all the bugs. Authentication should be a easy fix.

**Comment by philbertphotos** [comment]
I have not heard back s assume this is corrected.
