### ISSUE TITLE
Sync not working with ost 1.17.4

### ISSUE THREAD

**Issue by Fe3lApAcUt** [philbertphotos/osticket-multildap-auth-plugin#72]
Hey @philbertphotos 
Hope you're doing great!
I think the sync function is not working since I last tried osTicket again after a few months of abstinence. I'm using your latest version and ost 1.17.4.

- User creation ist working after the user logs in manually 
- User login is working afterwards with http passthru
- However, the initial sync is not working and not presenting any errors.
- Cron job is running without errors.
- DB table ldap_sync is not updated. 

Is there an easy fix to get this to work correctly? 

Best regards
Marcel

**Comment by malti1984** [comment]
Hey @philbertphotos

i install today your Plugin on my new osTicket System (V 1.18) and i have the same same error/issue as Marcel.

Thanks for the help.

Best regards
Andreas

**Comment by philbertphotos** [comment]
Hmmm @Fe3lApAcUt lots of strange problems ... this update should be rock solid since I updated and fixed so many bugs. I worked on this extensively and the changes in 1.18 would not cause a single issue. LDAP_SYNC only updates if they user is create or login via the plugin.

Turn on logs ... I need to see what it says when a user tries to login.  Did you do the connect test? What about the LDAP string any special characters?

**Comment by malti1984** [comment]
With Logs do you need?

for me it doesn't matter what I enter, for example, on the ldap server (i put a other ip), Connect Test says OK.

**Comment by malti1984** [comment]
what i must add for the cronjob, i don't understand this point sorry :)

**Comment by philbertphotos** [comment]
@malti1984 Logs here
![image](https://github.com/philbertphotos/osticket-multildap-auth-plugin/assets/2892474/75572f9c-a137-4749-a90f-6417e083cf88)
PHP Logs  and CRON LOGS if its separate from php log

**Comment by philbertphotos** [comment]
Yours woudl say "user login" since I have a new version that has some new features that I am still testing before release but its built off this base. 
I the connect says ok the LDAP is working (need to fix it so it shows all domains) The issue is the LDAP search if its the default then they should be no issues.

**Comment by philbertphotos** [comment]
Ok for got I updated the ldapclass ... it could be the reason it was not working properly but unlikely. In any case up date to that one and let me know.

**Comment by malti1984** [comment]
Hello, thanks for the help :-)

User creation ist working after the user logs in manually. Wan't sync the agents or user on my page.

Can you tell my, how i start the sync user manually?
And how i add the **cron job** for the sync? I don't understand this :)

on my config - every time i save, it's the same time
![grafik](https://github.com/philbertphotos/osticket-multildap-auth-plugin/assets/47427063/20e118a2-7081-4e39-9124-49c928d13a0e)

that's my sysmtelog, after saved config. That's all:
![grafik](https://github.com/philbertphotos/osticket-multildap-auth-plugin/assets/47427063/1982ece7-bbb5-4a7c-9bfa-03cf939c95ba)

when i try to login manually - i checked out "Register staff member to be registered automatically"
![grafik](https://github.com/philbertphotos/osticket-multildap-auth-plugin/assets/47427063/9fc43464-4f85-4af2-b556-2ab545690307)

Thanks alot

**Comment by malti1984** [comment]
Thanks, so i add the CronJob and the CronJob is running without errors.

The NEXT and LAST Schedule have the same TIME and DATE.
Then i check the php files and see that you look at the ost_config table.
there you search for **sync_data** and **namespace** (PLUGIN ID, INSTANCE ID).

on my installation (new installed with 1.17.4 and your plugin):
![grafik](https://github.com/philbertphotos/osticket-multildap-auth-plugin/assets/47427063/d9bee8a6-d8f2-4680-a2d0-c34143f9a163)
There ist no NAMESPACE on the SYNC_DATA line.

Then i change the line and now i see that the time has changed:
![grafik](https://github.com/philbertphotos/osticket-multildap-auth-plugin/assets/47427063/322d4b26-9218-44aa-9615-89c9d09c13fc)

Sync are running:
![grafik](https://github.com/philbertphotos/osticket-multildap-auth-plugin/assets/47427063/195061ba-4220-46df-abd6-9c725e6c0d23)

But no Agents where created?!

any idea?

thanks for your help

**Comment by philbertphotos** [comment]
Agents are not automatically created during sync (not until the next release) An agent can be created during login or manually created and they sync when changes in AD is detected.
As for plugin instance on the sync_data ... that is a GREAT catch now I have to find out why that was not created properly. Very strange that should have been fix. That is DEF a bug.

**Comment by malti1984** [comment]
Ok thanks, then i test the next day's the User SYNC. I install a new Debian Server and try it.
At the moment, no SYNC works on my Apache2 Server with PHP 8.0.

I see the User's when i search it under Users, but in the OSTicket Log i don't see the LDAP Sync.
Very strange, It show's the LDAP-Sync once.

I give you a feedback tomorrow

**Comment by philbertphotos** [comment]
This is me ... my environment is about 20 thousand users. So email like this is a regular occurrence. 
![image](https://github.com/philbertphotos/osticket-multildap-auth-plugin/assets/2892474/fd58f3a5-0e9c-4f26-b74d-a88917392745)

**Comment by philbertphotos** [comment]
Best thing to do is to change the schedule that way you can tell it worked with out wating for the next day. For testing I just tell it 5 minutes then change it back after it executed a few times.

**Comment by malti1984** [comment]
I change the sync an crontab to 2 minutes, but no sync and no email. I will try it tomorrow with a fresh installed osTicket Version.

**Comment by malti1984** [comment]
For me: the sync create User automatically or only when users Login First time? Like Agents?

Should i set to private Mode or Public in Settings?

**Comment by philbertphotos** [comment]
@malti1984 Syncing does not create a users it just updates existing accounts based on AD . For instance if I change the user name or other information it will get what ever is AD and overwrite OSTICKET.
Ina future version it will dump users not in OSticket from AD but personally I dont need this feature since users are automatically created when the login for the first time.

**Comment by philbertphotos** [comment]
@malti1984 modes no longer matter. I found a way around this and it creates users regardless what setting you have and yes ... only when user login for the first time.

**Comment by philbertphotos** [comment]
@Fe3lApAcUt looking at this bug.

**Comment by flimby1** [comment]
Hi, I have Sync problem too with the plugin on OsTicket 1.18.
I configured all and seems all correctly but I don't receive any Log on the system and also no email

**Comment by philbertphotos** [comment]
@flimby1  FIXED
