### ISSUE TITLE
Error 500 after saving plugin settings page

### ISSUE THREAD

**Issue by HofstadterK** [philbertphotos/osticket-multildap-auth-plugin#74]
Greetings!

I have a fresh install of osTicket 1.18 on WinServer 2022/IIS and only installed plugin is last version multi ldap. After I fill settings on instance page and click "save", i get "Plugin settings saved" message, but after that osTicket goes into brick mode, returning 500 on any attempt to connect, I can't even open the starting page. PHP log says this:

PHP Fatal error:  Uncaught OrmException: LdapMultiAuthPlugin: nstance: Field not defined in C:\inetpub\wwwroot\osticket\include\class.orm.php:413
Stack trace:
#0 C:\inetpub\wwwroot\osticket\include\class.orm.php(417): VerySimpleModel->get()
#1 C:\inetpub\wwwroot\osticket\include\plugins\multi-ldap\auth.php(334): VerySimpleModel->__get()
#2 C:\inetpub\wwwroot\osticket\include\plugins\multi-ldap\auth.php(379): LdapMultiAuthPlugin->logger()
#3 C:\inetpub\wwwroot\osticket\include\plugins\multi-ldap\auth.php(233): LdapMultiAuthPlugin->sync_copy()
#4 C:\inetpub\wwwroot\osticket\include\plugins\multi-ldap\auth.php(23): LdapMultiAuthPlugin->firstRun()
#5 C:\inetpub\wwwroot\osticket\include\class.plugin.php(1164): LdapMultiAuthPlugin->bootstrap()
#6 C:\inetpub\wwwroot\osticket\include\class.plugin.php(202): PluginInstance->bootstrap()
#7 C:\inetpub\wwwroot\osticket\include\class.osticket.php(685): PluginManager->bootstrap()
#8 C:\inetpub\wwwroot\osticket\main.inc.php(34): osTicket::start()
#9 C:\inetpub\wwwroot\osticket\scp\staff.inc.php(20): require_once('...')
#10 C:\inetpub\wwwroot\osticket\scp\admin.inc.php(16): require_once('...')
#11 C:\inetpub\wwwroot\osticket\scp\helptopics.php(16): require('...')
#12 {main}
  thrown in C:\inetpub\wwwroot\osticket\include\class.orm.php on line 413
  
Manual removing of plugin from include directory restores osTicket back.

**Comment by philbertphotos** [comment]
Ok I think is a bug that seems to only be a problem on a  in a FRESH install on osticket 1.8 I will fix it and make an update.

**Comment by HofstadterK** [comment]
Great! Thank you very much.

**Comment by HofstadterK** [comment]
Hi. Any luck with this issue? Maybe some dirty fix or workaround? No pressure at all, I just kinda have a deadline. : )

**Comment by philbertphotos** [comment]
I deleted the plugin and reinstalled several times from source of github and I cannot reproduce this error. Is it still happening no matter when you add it back?

**Comment by philbertphotos** [comment]
There can be a work around maybe

**Comment by philbertphotos** [comment]
send me a copy of this file 
C:\inetpub\wwwroot\osticket\include\plugins\multi-ldap\auth.php

**Comment by HofstadterK** [comment]
OK, i made once again fresh install of 1.18, clean as Mother Mary, not even language pack installed.  IIS/PHP 8.2.11. Same error after saving instance settings.  auth.php attached.
[auth.zip](https://github.com/philbertphotos/osticket-multildap-auth-plugin/files/13006934/auth.zip)

**Comment by philbertphotos** [comment]
@HofstadterK  Fixed .... found the issue just download the new update and fixing my versions :)
