### ISSUE TITLE
Users can't login

### ISSUE THREAD

**Issue by siilitman** [philbertphotos/osticket-multildap-auth-plugin#76]
I'm running osTicket v1.18
Debian 11
Apache 2.4.56
MySQL 10.5.21
PHP 8.1.23
Your plugin 1.7

The users are unable to login to the user front end by either username or email, it errors until you get too many failed logins and blocked.
There's nothing in the event logs to indicate why the user login is failing
Agent login via /scp is working fine

I've got the update to osTicket 1.18.1 queued along with the update to 1.8 for your plugin

I don't want to do either update until I resolve the problem but due to the lack of hints in the logs, I can't work out if it's a plugin problem or osTicket problem?!?

Can you offer any guidance?

**Comment by alepensato** [comment]
@siilitman I have the same problem using the "official" ldap plugin where i can login only as agent,

**Comment by philbertphotos** [comment]
@siilitman is this even still a problem?

**Comment by philbertphotos** [comment]
Fixed with latest release.
