### ISSUE TITLE
Not getting 2 Domain LDAP logins to work

### ISSUE THREAD

**Issue by cmwg71** [philbertphotos/osticket-multildap-auth-plugin#78]
I am using osTicket 1.18.1 with your current Multi LDAP 1.8 

Question 1:  1.18 has multiple instances for plugins, does your plugin support this? ie. create an instance per LDAP domain? or should the multi domains be added into one instance (separtion ;)? 

Question 2: i created one instance with the first domain and this worked instantly and very fast LDAP lookup. After adding 2nd instance for 2nd domain, both LDAP lookups don´t work. Putting it into one instance, does not work either. 

(for both above, the connection test always returns OK)

Question 3: there is nothing in the osTicket system logs noted - not even errors. Is there a server side log i should be looking at?

**Comment by cmwg71** [comment]
Not sure if this will help, trying to run sync_mldap.php from console i get the following back:

PHP Fatal error:  Uncaught Error: Class "LDAPMultiAuthentication" not found in /var/www/vhosts/******/******/include/plugins/multi-ldap/sync_mldap.php:16
Stack trace:
#0 {main}
  thrown in /var/www/vhosts/********/*********/include/plugins/multi-ldap/sync_mldap.php on line 16

**Comment by cmwg71** [comment]
Additionally i verified,  using instances:

seemingly only the first instance (in the order shown in the list) works, if both are active only results from the first are shown, if the first is inactive, no results are shown from the second.

**Comment by philbertphotos** [comment]
@cmwg71 that is interesting and in truth I assumed it would work without any changes and never actually tested it. I would have to figure out what instances look for when it comes to searches.,

sync_mldap.php cannot be ran directly.
Let me get back to you this weekend.

**Comment by cmwg71** [comment]
any news or progress?

**Comment by philbertphotos** [comment]
Let me check ... I am currently testing two instances with different domains. Never needed to do so since the plugin and do multiple domains on its own

**Comment by cmwg71** [comment]
how is the testing going?

**Comment by cmwg71** [comment]
Sorry to bug you, but have you had any progress? would really like to use your plugin for a productive osTicket site.

**Comment by philbertphotos** [comment]
@cmwg71  all fixed ...and you are not bothering me just a change in jobs caused some delays.
