### ISSUE TITLE
Plugin instance doesn't run on cron

### ISSUE THREAD

**Issue by sergejostir** [philbertphotos/osticket-multildap-auth-plugin#79]
Hello.

I tried on osTicket 1.18.1 and 1.17.5 and I cannot get the sync functionality to work. The connection to domain is working okay, but the synchronization never happens. I set Sync Schedule to "1 minute", but when I run the cron I can see in the system log that cron was run, but nothing regarding the plugin.

How do I diagnose this? PHP error log also doesn't show anything. 

Thanks

**Comment by philbertphotos** [comment]
Looking at that now may have been because of a new version of PHP so I had to update the LDAP api.

**Comment by Coros** [comment]
I believe I'm running into this same issue.  I can't get any LDAP Sync to run.

**Comment by hongz1** [comment]
Is this resolved? I installed osticket 1.18.1 and authentication works well, but ldap sync does not work.

**Comment by philbertphotos** [comment]
@hongz1 almost just a few more things to deal with.

**Comment by philbertphotos** [comment]
FIXED
