### ISSUE TITLE
Manually adding a user returns 404 error.

### ISSUE THREAD

**Issue by Coros** [philbertphotos/osticket-multildap-auth-plugin#81]
1. Login to OSTicket (v1.18) as an Agent.
2. Navigate to Users -> User Directory
3. Click Add User
4. Enter a user's email in the search field
5. Below the search field, a drop down appears with the discovered users.
6. Click a discovery user.
7. Nothing happens on screen. The web browser developer tools report a 404 error to https://server.domain.tld/scp/ajax.php/users/select/auth%3Amldap%3A (and continues on with the user's distinguished name)

Expected behavior: Step 7 should populate the fields in the Add user dialog with the information obtain from LDAP/Active Directory.  The standard LDAP auth plugin performs a similar http request when selecting a discovered user but is successful.

**Comment by eamkrc** [comment]
Hi, just to add same thing happens when Agents try to select a user not in the User Directory when creating a New Ticket on osTicket v1.17, plugin v1.8

**Comment by philbertphotos** [comment]
@Coros and @eamkrc working on both of these issues.

**Comment by philbertphotos** [comment]
FIXED
